[RUN]
run_name = test
# If set to 0, full trajectory, if set to 1, reentry only
run_type = 0
output_path = ./output
num_runs = 2
time_step_main = 1.0
time_step_reentry = 0.01
traj_output = 0
x_aim = 6371e3
y_aim = 0.0
z_aim = 0.0
theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
# Gravitational error model
grav_error = 0
# Atmospheric model
atm_model = 0
# Atmospheric perturbations
atm_error = 0
# Positioning updates during exoatmospheric flight
gnss_nav = 0
# If set to 0, indicates perfect acceleration measurements
ins_nav = 1
# If set to 1, enables idealized boost phase guidance
boost_guidance = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 1
# Reentry velocity (m/s) for reentry only simulation (run_type = 1)
reentry_vel = 7500

[VEHICLE]
rv_type = 1

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 0.0
initial_vel_error = 0.0
initial_angle_error = 0.0
acc_scale_stability = 0.0
gyro_bias_stability = 0.0
gyro_noise = 0.0
gnss_noise = 0.0
cl_pert = 0
# Step function acceleration magnitude (m/s^2)
step_acc_mag = 0
# Step function acceleration height (m)
step_acc_hgt = 0
# Step function acceleration duration (s)
step_acc_dur = 0