[RUN]
run_name = test
# If set to 0, full trajectory, if set to 1, reentry only
run_type = 0
output_dir = ./output
num_runs = 2
time_step_main = 1.0
time_step_reentry = 0.01
traj_output = 0
impact_output = 1
x_launch = 6371e3
y_launch = 0.0
z_launch = 0.0
x_aim = 1525536.630030 
y_aim = -4453698.585795
z_aim = 4292662.099131

theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
# Gravitational error model
grav_error = 0
# Atmospheric model: 0=exponential, 1=exponential+wind, 2=EarthGRAM
atm_model = 0
# Positioning updates during exoatmospheric flight
gnss_nav = 0
# If set to 0, indicates perfect acceleration measurements
ins_nav = 1
# If set to 1, enables idealized boost phase guidance
boost_guidance = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 1
rv_type = 1
# Reentry velocity (m/s) for reentry only simulation (run_type = 1)
reentry_vel = 7500

[VEHICLE]
booster_type = 0
# Deflection time (s) for control surfaces 
deflection_time = 0.0
# Actuator max force at max speed (kN)
actuator_force = 12.0
# Gearing ratio---greater values correspond to increased max force and decreased max speed
gearing_ratio = 1.0
# Navigation gain for proportional navigation guidance law
nav_gain = 5.0

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 0.0
initial_vel_error = 0.0
initial_angle_error = 0.0
acc_scale_stability = 0.0
gyro_bias_stability = 0.0
gyro_noise = 0.0
gnss_noise = 0.0
cl_pert = 0
# Perturbation of the angle of attack
aoa_pert = 0
# Step function acceleration magnitude (m/s^2)
step_acc_mag = 0
# Step function acceleration height (m)
step_acc_hgt = 0
# Step function acceleration duration (s)
step_acc_dur = 0