repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.4
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --select, I]

      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        files: \.(c|h)$

  - repo: local
    hooks:
      - id: generate-c-api-docs
        name: Generate C API docs
        entry: uv run docs/parser.py
        language: system
        pass_filenames: false
        always_run: true

      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy --extra-arg=-Isrc/include
        language: system
        files: ^src/.*\.(c|h)$

      - id: comptest
        name: Compile, Unit Test, and Build
        entry: bash scripts/comptest.sh --skip-integration
        language: system
        pass_filenames: false
        always_run: true
        verbose: true

      - id: integration-tests
        name: Integration Tests
        entry: bash scripts/comptest.sh --integration-only
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        verbose: true
