[project]
name = "pytrajlib"
version = "1.0.0-alpha.17"
description = "Simulate the flight of a ballistic or maneuverable missile"
readme = "README.md"
authors = [
    { name = "L.M. Arthur" },
    { name = "A.M. Decker" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scipy>=1.15.3",
    "tqdm>=4.67.3",
    "cffi>=2.0.0",
    "optuna>=4.9.0",
    "scienceplots>=2.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
    "setuptools>=82.0.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.3",
    "zensical>=0.0.44",
    "mkdocstrings>=1.0.4",
    "mkdocstrings-c>=0.1.0",
    "mkdocstrings-python>=2.0.4",
]

[project.scripts]
pytrajlib = "pytrajlib:cli"

[build-system]
requires = ["setuptools", "cffi"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = "uname -a"
