[project]
name = "pytrajlib"
version = "1.0.0-alpha.6"
description = "Simulate the flight of a ballistic or maneuverable missile"
readme = "README.md"
authors = [
    { name = "L.M. Arthur" },
    { name = "A.M. Decker" }
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
    "cffi>=1.17.1",
    "tqdm>=4.67.1",
    "scienceplots>=2.1.1",
]

[dependency-groups]
dev = [
    "mkdocstrings-c>=0.1.0",
    "zensical>=0.0.17",
    "mkdocstrings-python>=2.0.1",
    "pre-commit>=4.5.1",
    "build>=1.2.2.post1",
    "cibuildwheel>=2.23.3",
    "pytest>=8.3.5",
    "setuptools>=79.0.0",
    "ruff>=0.12.11",
]
jupyter = [
    "ipykernel>=6.29.5",
]

[project.scripts]
pytrajlib = "pytrajlib:run"

[build-system]
requires = ["setuptools", "cffi"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = "uname -a"
