[RUN]
run_name = "run_4"
num_runs = 30
num_runs_optimizer = 100
time_step_lambert = 0.01
time_step_midcourse = 0.01
time_step_atm = 0.01
traj_output = 1
# 100 longitude (~11e3 km range)
# Range is in meters
range = 11119492.664455872
# The aimpoint is superseded by the range
x_aim = -1106312.539916013
y_aim = 6274210.194440777
z_aim = 0
theta_long = 1.04719755
theta_lat = 0.0

# 0 is modified Euler-Maruyama, 1 is SRA3
integrator = 1

[FLIGHT]
# Gravitational error model
grav_error = 1
# Include aerodynamic drag force (1 on, 0 off)
include_drag = 1
# Atmospheric model. 0 is exponential, 1 is exponential with perturbations, 2 is EarthGram, 3 is mean EarthGram
atm_model = 2
# Positioning updates during exoatmospheric flight (1 is on, 0 is off)
gnss_nav = 1
# If set to 0, indicates perfect state measurements
ins_nav = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 1
# Reentry velocity (m/s)
reentry_vel = 7500
# If 0, indicates realistic boost, 1 perfect
perfect_boost = 1
# If 1, optimize t_des_final/theta_long. If 0, use provided values directly.
optimize_boost = 1
t_des_final = 2000
t_vert_boost = 10

[VEHICLE]
rv_type = 1
deflection_time = 0.02
actuator_force = 100
gearing_ratio = 1
nav_gain = 5
flap_gain = 100
# Vehicle parameter defaults (SWERVE RV + MMIII booster)
rv_mass = 450.0
rv_length = 2.75
rv_radius = 0.23
rv_c_d_0 = 0.1
rv_c_d_alpha = 0.487
booster_area = 2.2698
booster_maxdiam = 1.7
booster_c_d_0 = 0.15
booster_bus_mass = 100.0

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 0.1
initial_vel_error = 1e-3
initial_angle_error = 1e-6
acc_scale_stability = 1e-6
gyro_bias_stability = 1e-8
gyro_noise = 1e-8
gnss_noise = 1e-1
# GNSS update frequency in Hz
gnss_freq = 1.0
cl_pert = 0
# Step function acceleration magnitude (m/s^2)
step_acc_mag = 0
# Step function acceleration height (m)
step_acc_hgt = 0
# Step function acceleration duration (s)
step_acc_dur = 0