[RUN]
run_name = "run_4"
num_runs = 30
num_runs_optimizer = 50
num_trials_optimizer = 100
time_step_boost = 1e-3
time_step_lambert = 1e-4
time_step_midcourse = 1.0
time_step_reentry = 1e-4
traj_output = 1
# Range is in meters
range = 10000000
# The aimpoint is superseded by the range
x_aim = -1106312.539916013
y_aim = 6274210.194440777
z_aim = 0
theta_long = 0.6715065960788051
theta_lat = 0.0

# 0 is modified Euler-Maruyama, 1 is SRA3
integrator = 1
random_seed = -1

[FLIGHT]
# Gravitational error model
grav_error = 1
# Use simplified drag (1 on, 0 off)
ballistic_drag = 0
# Atmospheric model. 0 is exponential, 1 is exponential with perturbations, 2 is EarthGram, 3 is mean EarthGram
atm_model = 2
# Positioning updates during exoatmospheric flight (1 is on, 0 is off)
gnss_nav = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 1
# Reentry velocity (m/s)
reentry_vel = 7500
# If 0, indicates realistic boost, 1 perfect
perfect_boost = 0
# If 1, optimize t_des_final/theta_long. If 0, use provided values directly.
optimize_boost = 0
# If 1, optimize the maneuver parameters with `rv_maneuv` forced to 1 during optimization:
# `max_deflection_angle`, `nav_gain_0`, `nav_gain_1`, `K_q`, `K_pp`, `K_delta_p`, and `K_delta_d`.
optimize_reentry = 0
t_des_final = 2986.6467267274857
t_vert_boost = 10

[VEHICLE]
# Reentry vehicle type (0: ballistic, 1: maneuverable)
rv_type = 1
deflection_time = 0.02
actuator_force = 100
gearing_ratio = 18.902565748694002
actuator_resolution = 1e-2
max_deflection_angle = 5.005158800904358
nav_gain_0 = 17.16392199274926
nav_gain_1 = 1.8450079089106168
K_q = 9.93839564932045
K_pp = 12.011089458530302
K_delta_p = 0.2397109503235244
K_delta_d = 12.81326407331284


# Vehicle parameter defaults (SWERVE RV + MMIII booster)
rv_mass = 450.0
rv_length = 2.75
rv_radius = 0.23
rv_c_d_0 = 0.0180
rv_c_d_alpha = 0.487
rv_c_m_delta = 0.059
booster_area = 2.2698
booster_maxdiam = 1.7
booster_c_d_0 = 0.15
booster_bus_mass = 100.0

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 0.1
initial_vel_error = 1e-3
initial_angle_error = 1e-6
acc_scale_stability = 1e-6
gyro_bias_stability = 1e-8
gyro_noise = 1e-8
gnss_noise = 1e-1
# GNSS update frequency in Hz
gnss_freq = 1.0
cd_error_factor = 1.0
cl_error_factor = 1.0
cmq_error_factor = 1.0
cm_error_factor = 1.0
cm_delta_error_factor = 1.0
roll_gyro_error_factor = 0.0
rv_mass_scale_factor = 1.0
burn_time_error = 1.0
